### ISSUE TITLE
This is not a problem but me trying...

### ISSUE THREAD

**Issue by Smario9000** [Chris-Is-Awesome/Extra2DewMod#1]
Hi Chris-Is-Awesome
i am trying to get in touch with you to see if you can help me with something. i am trying to make a mod for a game and your game is close to what i am working on.
so some info
i am trying to make a randomize mod to Ittle Dew, and i wanted to see if you would be cool to help me understand how you did yours.
please help i dont know who else to turn to
i have no idea what i am doing and i want to to do this. i have never made anything and i want to make something. please help...

Thanks for taking the time to read this

**Comment by Chris-Is-Awesome** [comment]
Hey, there's a lot that goes into modding a game, but I'll give a quick summary:

When modding any game, the first thing you need to know is what engine it uses. You can find this by looking at the game's files, as each engine has their own distinctive file structure. Ittle Dew (as with all main Ludo games) are made in Unity.

We use a program called Dnspy, a C# decompiler that lets us edit the game's code (for Unity games not using IL2CPP). Most code for the game is stored in the `Assembly-CSharp.dll` file in the game's files which you open in Dnspy.

We've also extracted the game assets and rebuilt our own Unity project so we can further test things in Unity and use AssetBundles (better way of loading adding custom assets to the game), but this is a much more advanced topic, usually not required for a randomizer.

As for the writing of the randomizer itself, that ultimately comes down to how you want to approach it. There are different randomization algorithms you can use for generating "playthroughs" to ensure it's beatable. Here's a good video that covers all the types and how some Zelda randomizers handled development https://youtu.be/vGIDzGvsrV8 (note: they talk more from the console game modding perspective, which is much harder and usually requires Assembly/C++, but you can ignore all that mumbo jumbo for a Unity game).

You will need to reverse engineer the game's code to understand how to make the modifications you want. Ittle Dew''s code is much messier and less intuitive than its sequel, so good luck with that :)

Not to be discouraging, but making any modification to a game isn't a simple task. It can take months for you to know enough about the game to know how to make the change. In the case of Extra 2 Dew, this has been a project for 4 years, and we still don't know everything about the game's code, though we are at the point where we can do almost anything we want.

If you want more specifics or to talk with the other devs for this mod directly, feel free to join our Ludo Modding Discord server: https://discord.gg/6jfVvvqE
